<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Why Are Employees Leaving?</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="employee_attrition_files/libs/clipboard/clipboard.min.js"></script>
<script src="employee_attrition_files/libs/quarto-html/quarto.js"></script>
<script src="employee_attrition_files/libs/quarto-html/popper.min.js"></script>
<script src="employee_attrition_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="employee_attrition_files/libs/quarto-html/anchor.min.js"></script>
<link href="employee_attrition_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="employee_attrition_files/libs/quarto-html/quarto-syntax-highlighting-e26003cea8cd680ca0c55a263523d882.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="employee_attrition_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="employee_attrition_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="employee_attrition_files/libs/bootstrap/bootstrap-973236bd072d72a04ee9cd82dcc9cb29.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Why Are Employees Leaving?</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Employee attrition, the departure of employees from an organization, presents a significant and multifaceted challenge. High turnover rates can have far-reaching consequences, impacting not only financial performance but also organizational culture and long-term sustainability. These consequences include:</p>
<ul>
<li><strong>Loss of Institutional Knowledge:</strong> The departure of long-tenured employees results in the loss of invaluable expertise, specialized skills, and deep understanding of organizational processes. This “brain drain” can hinder innovation and efficiency.</li>
<li><strong>Substantial Financial Costs:</strong> The process of replacing employees is expensive. It encompasses recruitment advertising, interviewing, onboarding, and training new hires. These costs are amplified when turnover is consistently high, diverting resources from other critical areas.</li>
<li><strong>Disrupted Performance and Morale:</strong> High turnover disrupts team workflows, creating instability and uncertainty. Remaining employees may experience increased workloads, stress, and decreased morale, leading to lower productivity and engagement.</li>
<li><strong>Impaired Talent Acquisition:</strong> A reputation for high employee turnover can significantly damage an organization’s ability to attract and retain top talent. Potential candidates may perceive the company as unstable or lacking in employee support and development opportunities.</li>
<li><strong>Negative Brand Reputation:</strong> Beyond recruitment, high turnover can negatively impact an organization’s overall image. Customers, partners, and the wider community may perceive the company as poorly managed or undesirable to work for.</li>
</ul>
<section id="identifying-and-addressing-high-turnover" class="level2">
<h2 class="anchored" data-anchor-id="identifying-and-addressing-high-turnover">Identifying and Addressing High Turnover</h2>
<p>Analyzing organizational and employee data can provide a clear understanding of the contributing factors influencing turnover. Only then can I develop data-driven targeted recommendations and interventions to address them.</p>
<p>To investigate the drivers of employee attrition, I analyze a dataset containing information on various employee characteristics and work-life factors. This dataset allows me to explore potential relationships between these factors and an employee’s decision to leave the company. I will begin with exploratory data analysis to visualize patterns and trends, and then I will build a statistical model to predict the likelihood of attrition based on these key factors.</p>
</section>
<section id="initial-exploration-understanding-the-landscape-of-attrition" class="level2">
<h2 class="anchored" data-anchor-id="initial-exploration-understanding-the-landscape-of-attrition">Initial Exploration: Understanding the Landscape of Attrition</h2>
<p>Before diving into specific factors, I begin by gaining a broad understanding of the dataset. I examine the distribution of key variables, paying attention to how these distributions differ between employees who have left the company (Attrition = Yes) and those who remain (Attrition = No). This initial exploration helps me identify potential areas of interest and formulate hypotheses about the drivers of attrition.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="employee_attrition_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="employee_attrition_files/figure-html/unnamed-chunk-4-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="employee_attrition_files/figure-html/unnamed-chunk-4-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="employee_attrition_files/figure-html/unnamed-chunk-4-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="employee_attrition_files/figure-html/unnamed-chunk-4-5.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="employee_attrition_files/figure-html/unnamed-chunk-4-6.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="employee_attrition_files/figure-html/unnamed-chunk-4-7.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="employee_attrition_files/figure-html/unnamed-chunk-4-8.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="research-questions" class="level2">
<h2 class="anchored" data-anchor-id="research-questions">Research Questions</h2>
<p>My initial exploration suggests a potential link between work-life balance and employee attrition. To investigate this further, I focus on the following key research questions:</p>
<ol type="1">
<li><p><strong>Primary Question:</strong> How do key work-life balance factors (business travel, overtime, distance from home, and self-reported work-life balance) influence the likelihood of employee attrition?</p></li>
<li><p><strong>Secondary Question:</strong> Do the effects of these work-life balance factors on attrition differ across employee subgroups (age, job role, and department)?</p></li>
</ol>
<p><strong>Variables of Interest:</strong></p>
<ul>
<li><strong>Outcome Variable:</strong> Attrition (binary: Yes/No)</li>
<li><strong>Predictor Variables (Work-Life Balance):</strong>
<ul>
<li>BusinessTravel (categorical)</li>
<li>DistanceFromHome (numeric)</li>
<li>OverTime (binary: Yes/No)</li>
<li>WorkLifeBalance (numeric, treated as ordinal)</li>
</ul></li>
<li><strong>Grouping Variables (for Subgroup Analysis):</strong>
<ul>
<li>JobRole (categorical)</li>
<li>Age (numeric)</li>
<li>Department (categorical)</li>
</ul></li>
</ul>
</section>
<section id="analyzing-work-life-balance-variables-a-deeper-dive" class="level2">
<h2 class="anchored" data-anchor-id="analyzing-work-life-balance-variables-a-deeper-dive">Analyzing Work-Life Balance Variables: A Deeper Dive</h2>
<p>Having established the importance of work-life balance in my research question, I now examine specific variables related to this theme: Business Travel, Distance From Home, OverTime, and WorkLifeBalance.</p>
<p>I aim to understand how each of these factors relates to employee attrition, and whether these relationships support my initial hypotheses.</p>
<section id="business-travel-grouped-by-attrition" class="level3">
<h3 class="anchored" data-anchor-id="business-travel-grouped-by-attrition">Business Travel grouped by Attrition</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="employee_attrition_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="interpretation-and-insights" class="level4">
<h4 class="anchored" data-anchor-id="interpretation-and-insights">Interpretation and Insights:</h4>
<p>The plot reveals a clear association between business travel frequency and attrition: <strong>Employees who travel frequently are significantly more likely to leave the company compared to those who travel rarely or not at all</strong>. This suggests that the demands and potential stress associated with frequent travel may contribute to burnout and dissatisfaction, leading to higher turnover.</p>
<p>This finding highlights a potential area for intervention: the company could explore ways to reduce the burden of frequent travel. This could include: - Offering more flexible travel arrangements - Providing additional support to frequent travelers - Re-evaluating the necessity of certain trips</p>
<hr>
</section>
</section>
<section id="distance-from-home-grouped-by-attrition" class="level3">
<h3 class="anchored" data-anchor-id="distance-from-home-grouped-by-attrition">Distance from home grouped by Attrition</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="employee_attrition_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="interpretation-and-insights-1" class="level4">
<h4 class="anchored" data-anchor-id="interpretation-and-insights-1">Interpretation and Insights:</h4>
<p>The density plot indicates a higher concentration of former employees (Attrition = Yes) living further from the office. While not a definitive causal relationship, this suggests that longer commutes may contribute to attrition. This could be due to increased stress, reduced work-life balance, or a weaker connection to the company culture.</p>
<p>This finding could inform decisions about remote work policies, flexible work arrangements, or even the provision of transportation assistance. It’s important to note the overlap in distributions; many employees with longer commutes do stay, indicating other factors are also at play.</p>
<hr>
</section>
<section id="overtime-grouped-by-attrition" class="level4">
<h4 class="anchored" data-anchor-id="overtime-grouped-by-attrition">Overtime grouped by Attrition</h4>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="employee_attrition_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="interpretation-and-insights-2" class="level4">
<h4 class="anchored" data-anchor-id="interpretation-and-insights-2">Interpretation and Insights:</h4>
<p>The bar plot clearly shows that employees who work overtime are considerably more likely to leave the company. This strongly suggests that excessive work hours contribute to attrition, potentially due to burnout, reduced work-life balance, and increased stress.</p>
<p>This is a critical area for HR to address. Possible interventions could include workload management strategies, stricter overtime policies, or increased staffing levels.</p>
<hr>
</section>
</section>
<section id="work-life-balance-survey-grouped-by-attrition" class="level3">
<h3 class="anchored" data-anchor-id="work-life-balance-survey-grouped-by-attrition">Work-life Balance Survey grouped by Attrition</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="employee_attrition_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="interpretation-and-insights-3" class="level4">
<h4 class="anchored" data-anchor-id="interpretation-and-insights-3">Interpretation and Insights:</h4>
<p>The plot shows a notable difference in attrition rates based on employee-reported work-life balance scores. Employees who rated their work-life balance as “1” (presumably the lowest rating) were significantly more likely to leave. While those with ratings of “2,” “3,” and “4” also show attrition, the rate is much lower.</p>
<p>This reinforces the importance of perceived work-life balance as a key factor in employee retention. The company should prioritize initiatives that promote a healthy work-life balance, such as flexible work arrangements, wellness programs, and clear expectations regarding working hours. It’s crucial to understand why some employees report such low work-life balance scores.</p>
<hr>
</section>
</section>
</section>
<section id="regression" class="level2">
<h2 class="anchored" data-anchor-id="regression">Regression</h2>
<section id="modeling-attrition-quantifying-the-impact-of-work-life-balance" class="level3">
<h3 class="anchored" data-anchor-id="modeling-attrition-quantifying-the-impact-of-work-life-balance">Modeling Attrition: Quantifying the Impact of Work-Life Balance</h3>
<p>Based on my exploratory analysis, which highlighted potential relationships between work-life balance factors and attrition, I now build a logistic regression model. This model allows me to quantify the impact of these factors on the <em>probability</em> of an employee leaving the company, while controlling for other variables. I specifically focus on WorkLifeBalance, BusinessTravel, DistanceFromHome, and OverTime, as these variables showed the strongest visual associations with attrition in my earlier analysis.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Attrition_binary ~ WorkLifeBalance + BusinessTravel + 
    DistanceFromHome + OverTime, family = "binomial", data = wlb_vars)

Coefficients:
                                 Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)                     -2.515951   0.435086  -5.783 7.35e-09 ***
WorkLifeBalance                 -0.238124   0.103918  -2.291  0.02194 *  
BusinessTravelTravel_Rarely      0.676579   0.320771   2.109  0.03493 *  
BusinessTravelTravel_Frequently  1.329089   0.340672   3.901 9.56e-05 ***
DistanceFromHome                 0.025202   0.008771   2.873  0.00406 ** 
OverTimeYes                      1.315862   0.148905   8.837  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 1298.6  on 1469  degrees of freedom
Residual deviance: 1182.3  on 1464  degrees of freedom
AIC: 1194.3

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
<section id="interpretation-and-insights-4" class="level4">
<h4 class="anchored" data-anchor-id="interpretation-and-insights-4">Interpretation and Insights</h4>
<p>The logistic regression model confirms my visual observations and provides quantifiable insights:</p>
<ul>
<li><p>WorkLifeBalance (-0.24): A better work-life balance is associated with a lower probability of attrition. This coefficient suggests that interventions aimed at improving work-life balance (e.g., flexible work, wellness programs) could have a measurable impact on reducing attrition.</p></li>
<li><p>BusinessTravel:</p>
<ul>
<li>Travel Rarely (0.68): Employees who travel rarely are more likely to leave compared to those who don’t travel at all.<br>
</li>
<li>Travel Frequently (1.33): Employees who travel frequently are even more likely to leave than those who travel rarely. The significant positive coefficients for both “Travel Rarely” and “Travel Frequently” (compared to “Non-Travel”) highlight the importance of addressing the challenges associated with business travel. The company should investigate the specific reasons why even rare travel is associated with higher attrition.</li>
</ul></li>
<li><p>DistanceFromHome (0.03): For every additional unit (like mile or kilometer) further away from home an employee lives, the likelihood of leaving increases slightly. Even a small increase in the coefficient for distance suggests that, all else being equal, employees with longer commutes are slightly more likely to leave. This reinforces the potential value of remote work options or relocation assistance.</p></li>
<li><p>OverTime (1.32): Employees who have to work overtime are significantly more likely to leave the company. The large positive coefficient for OverTime provides strong statistical evidence that working overtime is a significant predictor of attrition. This highlights the urgency of addressing workload imbalances and promoting a culture that values work-life balance.</p></li>
</ul>
<p><strong>Notably, these coefficients represent the independent effect of each factor, holding the other factors constant</strong>. For example, even after accounting for distance from home and work-life balance, working overtime still significantly increases the likelihood of attrition.</p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>